if(ANDROID)
    set(vulkan_libs__FOUND ON)
    if(ANDROID_STANDALONE_TOOLCHAIN)
        include_directories("${ANDROID_STANDALONE_TOOLCHAIN}/usr/include")
    endif()
    add_definitions(-DVK_USE_PLATFORM_ANDROID_KHR=1)
    set(vulkan_libs__LINKED android vulkan)
    
else()
    find_package(Vulkan REQUIRED)
    if (Vulkan_FOUND)
        set(vulkan_libs__FOUND ON)
        
        include_directories(${Vulkan_INCLUDE_DIRS})
        if(WIN32 OR WIN64 OR _WIN32 OR _WIN64)
            set(vulkan_libs__LINKED ${Vulkan_LIBRARIES})
            add_definitions(-DVK_USE_PLATFORM_WIN32_KHR=1)
        elseif(APPLE)
            set(vulkan_libs__LINKED ${Vulkan_LIBRARIES})
        else()
            set(vulkan_libs__LINKED X11 ${Vulkan_LIBRARIES})
        endif()
    endif()
endif()
